# Файл: docker-compose.yml
# Описание: Запускает базу данных PostgreSQL с расширением pgvector.
# PostgreSQL будет доступен на порту 5432 вашего компьютера.
version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: your_user         # Замените на ваше имя пользователя
      POSTGRES_PASSWORD: your_password # Замените на ваш пароль
      POSTGRES_DB: legal_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: